apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: polaris-limiter
  name: polaris-limiter
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: polaris-limiter
  serviceName: polaris-limiter
  template:
    metadata:
      labels:
        app: polaris-limiter
    spec:
      containers:
        - image: polarismesh/polaris-limiter:##LIMITER_SERVER_VERSION##
          imagePullPolicy: Always
          name: polaris-limiter
          resources:
            limits:
              cpu: "500m"
              memory: 1000Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /root/polaris-limiter.yaml.example
              name: polaris-limiter-config
              subPath: polaris-limiter.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 640
            name: polaris-limiter-config
          name: polaris-limiter-config
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
