name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

# Always force the use of Go modules
env:
  GO111MODULE: on

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      # Setup the environment.
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.5
      # Checkout latest code
      - name: Checkout repo
        uses: actions/checkout@v2

      # Compile
      - name: Build server
        run: bash build.sh